- name: create pagure config dir
  file:
    path: /etc/pagure
    state: directory

- name: install pagure configuration
  template:
    src: "{{ item }}.j2"
    dest: /etc/pagure/{{ item }}
  with_items:
    - pagure.cfg
    - alembic.ini

- name: create pagure folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /srv/git
    - /srv/docs
    - /srv/requests
    - /srv/remotes

- name: create pagure dir
  file:
    path: /usr/share/pagure
    state: directory

- name: install createdb
  copy:
    src: /srv/pagure/createdb.py
    dest: /usr/share/pagure/pagure_createdb.py
    remote_src: true

- name: enable wsgi apache module
  apache2_module:
    state: present
    name: wsgi

- name: install apache config
  copy:
    src: /srv/pagure/files/pagure.wsgi
    dest: /usr/share/pagure/pagure.wsgi
    remote_src: true

- name: install apache site
  template:
    src: pagure.conf.j2
    dest: /etc/apache2/sites-available/pagure.conf